config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'


  root 'articles#index'


  
  get "/create",to:"static_pages#create" 
  get "/profile",to:"static_pages#profile" 
  get  "/signup",  to: "users#new"



  #get  "/help", to: "static_pages#help"
  resources :users
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"


  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, length: { minimum: 5, maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  attr_accessor :remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

                    has_secure_password


  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end


   # 渡された文字列のハッシュ値を返す
   def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   # 渡されたトークンがダイジェストと一致したらtrueを返す
   def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all.order("created_at DESC")
  end
  
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article created!"
      redirect_to root_url
    else
      # 適切なエラーページにレンダリングするか、またはホームページに戻るなど、エラー処理を適切に設定します。
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "記事を更新しました"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "記事は削除されました"
     redirect_to user_path(@article.user)
  end

    private
# Strong Parametersを使用して安全に記事データを扱うためのメソッドです。
# 必要なパラメーターをここで許可してください。
def article_params
  params.require(:article).permit(:title, :description, :body)
end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



  def new
  end

  

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session      # ログインの直前に必ずこれを書くこと
      remember user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = '間違ってます！'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def article
  end

  def create

  end

  def edit

  end

  def profile
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = "登録が完了しました！"
      log_in @user
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
    # @articles = @user.articles.paginate(page: params[:page])
     @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user && current_user == user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

   # ユーザーがログインしていればtrue、その他ならfalseを返す
   def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    reset_session
    @current_user = nil   # 安全のため
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/articles/_article.hml.erb
<li id="article-<%= article.id %>">
  <%= link_to gravatar_for(article.user, size: 50), article.user %>
  <span class="user"><%= link_to article.user.name, article.user %></span>
  <span class="content"><%= article.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(article.created_at) %> ago.
  </span>
</li>

app/views/articles/edit.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <% if @article.errors.any? %>
          <ul class="error-messages">
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with(model: @article, local: true) do |form| %>
          <fieldset>
            <fieldset class="form-group">
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: "What's this article about?" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_area :body, class: "form-control", rows: "8", placeholder: "Write your article (in markdown)" %>
            </fieldset>
            
            <%= form.submit "記事を更新する", class: "btn btn-lg pull-xs-right btn-primary" %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>




<%# <fieldset class="form-group">
              <%= form.text_field :tag_list, class: "form-control", placeholder: "Enter tags" %>
              <%# <div class="tag-list"> %>
                <%# <% @article.tag_list.each do |tag| %>
                  <%# <span class="tag-default tag-pill"> %>
                    <%# <i class="ion-close-round"></i> <%= tag %> 
                  <%# </span> %>
                <%# <% end %> 
              <%# </div> %>
            <%# </fieldset> %> 

app/views/articles/index.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="#">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>

        <% @articles.each do |article| %>
<div class="article-preview">
  <div class="article-meta">
    <%= link_to gravatar_for(article.user), user_path(article.user) %>
    <div class="info">
      <%= link_to article.user.name, user_path(article.user), class: 'author' %>
      <span class="date"><%= article.created_at.strftime("%B %d") %></span>
    </div>
    <button class="btn btn-outline-primary btn-sm pull-xs-right">
      <i class="ion-heart"></i> 29
    </button>
  </div>
  <%= link_to article_path(article), class: "preview-link" do %>
    <h1><%= article.title %></h1>
    <p><%= article.description %></p>
    <span>Read more...</span>
    <ul class="tag-list">
      <li class="tag-default tag-pill tag-outline">realworld</li>
      <li class="tag-default tag-pill tag-outline">implementations</li>
    </ul>
  <% end %>
</div>
 <% end %>

        <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <% if @article.errors.any? %>
          <ul class="error-messages">
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with(model: @article, local: true) do |form| %>
          <fieldset>
            <fieldset class="form-group">
              <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: "What's this article about?" %>
            </fieldset>
            <fieldset class="form-group">
              <%= form.text_area :body, class: "form-control", rows: "8", placeholder: "Write your article (in markdown)" %>
            </fieldset>
            
            <%= form.submit "Publish Article", class: "btn btn-lg pull-xs-right btn-primary" %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>




<%# <fieldset class="form-group">
              <%= form.text_field :tag_list, class: "form-control", placeholder: "Enter tags" %>
              <%# <div class="tag-list"> %>
                <%# <% @article.tag_list.each do |tag| %>
                  <%# <span class="tag-default tag-pill"> %>
                    <%# <i class="ion-close-round"></i> <%= tag %> 
                  <%# </span> %>
                <%# <% end %> 
              <%# </div> %>
            <%# </fieldset> %> 

app/views/articles/show.html.erb
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>

      <div class="article-meta">
       <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <div class="info">
         <%= link_to @article.user.name, user_path(@article.user), class: 'author' %>
          <!-- 記事の作成日を表示 -->
          <span class="date"><%= @article.created_at.strftime("%B %d, %Y") %></span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; <%= @article.user.name %> <span class="counter">(10)</span>
        </button>
        &nbsp;&nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Post <span class="counter">(29)</span>
        </button>
        <%= link_to edit_article_path(@article), class: "btn btn-sm btn-outline-secondary" do %>
          <i class="ion-edit"></i> Edit Article
            <% end %>
            <%# ログインしているユーザーにしかdeleteボタンが表示されないようにする %>
         <% if current_user?(@article.user) %>
            <%= link_to article_path(@article), data: { turbo_method: :delete, turbo_confirm: '消してもよいですか？' }, class: "btn btn-sm btn-outline-danger" do %>
            <i class="ion-trash-a"></i> Delete Article
    <% end %>
<% end %>


       
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p>
         <%= @article.description %>
        <h2 id="introducing-ionic">Introducing RealWorld.</h2>
        <p> <%= @article.body.html_safe %></p>
        <ul class="tag-list">
          <li class="tag-default tag-pill tag-outline">realworld</li>
          <li class="tag-default tag-pill tag-outline">implementations</li>
        </ul>
      </div>
    </div>

    <hr />

    <div class="article-actions">
      <div class="article-meta">
         <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <div class="info">
          <%= link_to @article.user.name, user_path(@article.user), class: 'author' %>
          <span class="date">January 20th</span>
        </div>

        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons
        </button>
        &nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Article <span class="counter">(29)</span>
        </button>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-edit"></i> Edit Article
        </button>
        <button class="btn btn-sm btn-outline-danger">
          <i class="ion-trash-a"></i> Delete Article
        </button>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <form class="card comment-form">
          <div class="card-block">
            <textarea class="form-control" placeholder="Write a comment..." rows="3"></textarea>
          </div>
          <div class="card-footer">
            <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            <button class="btn btn-sm btn-primary">Post Comment</button>
          </div>
        </form>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
            <span class="mod-options">
              <i class="ion-trash-a"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <a href="/" class="logo-font">conduit</a>
    <span class="attribution">
      An interactive learning project from <a href="https://thinkster.io">Thinkster</a>. Code &amp;
      design licensed under MIT.
    </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <% if logged_in? %>
 <nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">conduit</a>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <!-- Add "active" class when you're on that page" -->
        <a class="nav-link active" href="/">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to new_article_path, class: 'nav-link' do %>
  <i class="ion-compose"></i>&nbsp;New Article
      <% end %>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="/settings"> <i class="ion-gear-a"></i>&nbsp;Settings </a>
      </li>
      <li class="nav-item">
       <%= link_to current_user.name, user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
      <%= link_to "Log out", logout_path,
                                       data: { "turbo-method": :delete },class: 'nav-link'%>
        </li>
    </ul>
  </div>
</nav>
<% else %>
  
<nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">conduit</a>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <!-- Add "active" class when you're on that page" -->
        <a class="nav-link active" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login">Sign in</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign up', signup_path, class: 'nav-link' %>

      </li>
    </ul>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8" />
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <title>Conduit</title>
  <!-- Import Ionicon icons & Google Fonts our Bootstrap theme relies on -->
  <link
    href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    rel="stylesheet"
    type="text/css"
  />
  <link
    href="//fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic"
    rel="stylesheet"
    type="text/css"
  />
  <!-- Import the custom Bootstrap 4 theme from our hosted CDN -->
  <link rel="stylesheet" href="//demo.productionready.io/main.css" />
    <%= javascript_importmap_tags %>
</head>

  <body>
     <%= render 'layouts/header' %>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/create.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <ul class="error-messages">
          <li>That title is required</li>
        </ul>

        <form>
          <fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control form-control-lg" placeholder="Article Title" />
            </fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control" placeholder="What's this article about?" />
            </fieldset>
            <fieldset class="form-group">
              <textarea
                class="form-control"
                rows="8"
                placeholder="Write your article (in markdown)"
              ></textarea>
            </fieldset>
            <fieldset class="form-group">
              <input type="text" class="form-control" placeholder="Enter tags" />
              <div class="tag-list">
                <span class="tag-default tag-pill"> <i class="ion-close-round"></i> tag </span>
              </div>
            </fieldset>
            <button class="btn btn-lg pull-xs-right btn-primary" type="button">
              Publish Article
            </button>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="profile_path">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>

        <div class="article-preview">
          <div class="article-meta">
            <a href="/profile/eric-simons"><img src="http://i.imgur.com/Qr71crq.jpg" /></a>
            <div class="info">
              <a href="/profile/eric-simons" class="author">Eric Simons</a>
              <span class="date">January 20th</span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> 29
            </button>
          </div>
          <a href="/article/how-to-build-webapps-that-scale" class="preview-link">
            <h1>How to build webapps that scale</h1>
            <p>This is the description for the post.</p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline">realworld</li>
              <li class="tag-default tag-pill tag-outline">implementations</li>
            </ul>
          </a>
        </div>

        <div class="article-preview">
          <div class="article-meta">
            <a href="/profile/albert-pai"><img src="http://i.imgur.com/N4VcUeJ.jpg" /></a>
            <div class="info">
              <a href="/profile/albert-pai" class="author">Albert Pai</a>
              <span class="date">January 20th</span>
            </div>
            <button class="btn btn-outline-primary btn-sm pull-xs-right">
              <i class="ion-heart"></i> 32
            </button>
          </div>
          <a href="/article/the-song-you" class="preview-link">
            <h1>The song you won't ever stop singing. No matter how hard you try.</h1>
            <p>This is the description for the post.</p>
            <span>Read more...</span>
            <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline">realworld</li>
              <li class="tag-default tag-pill tag-outline">implementations</li>
            </ul>
          </a>
        </div>

        <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>
      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <a href="" class="tag-pill tag-default">programming</a>
            <a href="" class="tag-pill tag-default">javascript</a>
            <a href="" class="tag-pill tag-default">emberjs</a>
            <a href="" class="tag-pill tag-default">angularjs</a>
            <a href="" class="tag-pill tag-default">react</a>
            <a href="" class="tag-pill tag-default">mean</a>
            <a href="" class="tag-pill tag-default">node</a>
            <a href="" class="tag-pill tag-default">rails</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="auth-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-xs-12">
        <h1 class="text-xs-center">Sign up</h1>
        <p class="text-xs-center">
          <a href="/login">Have an account?</a>
        </p>

        <% if @user.errors.any? %>
          <ul class="error-messages">
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_for(@user) do |f| %>
          <fieldset class="form-group">
            <%= f.text_field :name, class: 'form-control form-control-lg', placeholder: 'Username' %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.email_field :email, class: 'form-control form-control-lg', placeholder: 'Email' %>
          </fieldset>
          <fieldset class="form-group">
            <%= f.password_field :password, class: 'form-control form-control-lg', placeholder: 'Password' %>
          </fieldset>
          <%= f.submit "Sign up", class: "btn btn-lg btn-primary pull-xs-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-page">
  <div class="user-info">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-10 offset-md-1">
          <%= gravatar_for @user %>
          <h4><%= @user.name %></h4>
          <p>
            Cofounder @GoThinkster, lived in Aol's HQ for a few months, kinda looks like Peeta from
            the Hunger Games
          </p>
          <button class="btn btn-sm btn-outline-secondary action-btn">
            <i class="ion-plus-round"></i>
            &nbsp; Follow Eric Simons
          </button>
          <button class="btn btn-sm btn-outline-secondary action-btn">
            <i class="ion-gear-a"></i>
            &nbsp; Edit Profile Settings
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1">
        <div class="articles-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link active" href="">My Articles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Favorited Articles</a>
            </li>
          </ul>
        </div>
        
     <%# ここからArticleのまとまり %>
<% @articles.each do |article| %>
  <div class="article-preview">
    <div class="article-meta">
      <%= link_to gravatar_for(@user), user_path(current_user) %>

      <div class="info">
        <%= link_to current_user.name, user_path(current_user), class: 'author' %>
        <span class="date"><%= article.created_at.strftime("%B %d, %Y") %></span>
      </div>
      <button class="btn btn-outline-primary btn-sm pull-xs-right">
        <i class="ion-heart"></i> 29
      </button>
    </div>
    
   <%= link_to article_path(article), class: "preview-link" do %>
     
        <h1><%= article.title %></h1>
        <p><%= article.description %></p>
        <span>Read more...</span>
        <!-- ここに記事のタグを表示するためのコードを追加 -->
         <ul class="tag-list">
              <li class="tag-default tag-pill tag-outline">realworld</li>
              <li class="tag-default tag-pill tag-outline">implementations</li>
            </ul>
      </a>
    <% end %>
  </div>
<% end %>

<%# ここまで %>





        

       

        <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>